/*
The Fibonacci sequence is the series of numbers 0, 1, 1, 2, 3, 5, 8, ....
Formally, it can be expressed as:
fib0 = 0
fib1 = 1
fibn = fibn−1 + fibn−2
Write a multithreaded program that generates the Fibonacci sequence. This
program should work as follows: On the command line, the user will enter the
number of Fibonacci numbers that the program is to generate. The program
will then create a separate thread that will generate the Fibonacci numbers,
placing the sequence in data that can be shared by the threads (an array is
probably the most convenient data structure). When the thread finishes
execution, the parent thread will output the sequence generated by the child
thread. Because the parent thread cannot begin outputting the Fibonacci
sequence until the child thread finishes, the parent thread will have to wait for
the child thread to finish.
*/

#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>

// Global pointer to Fibonacci array and length
int *fib_array;
int count;

// Thread function to generate Fibonacci sequence
void* generate_fibonacci(void* arg) {
    if (count > 0) fib_array[0] = 0;
    if (count > 1) fib_array[1] = 1;
    for (int i = 2; i < count; i++) {
        fib_array[i] = fib_array[i - 1] + fib_array[i - 2];
    }
    pthread_exit(NULL);
}

int main(int argc, char *argv[]) {
    if (argc != 2) {
        fprintf(stderr, "Usage: %s <number of Fibonacci numbers>\n", argv[0]);
        exit(EXIT_FAILURE);
    }

    count = atoi(argv[1]);
    if (count < 1) {
        fprintf(stderr, "Count must be a positive integer.\n");
        exit(EXIT_FAILURE);
    }

    // Allocate memory for Fibonacci numbers
    fib_array = (int*) malloc(sizeof(int) * count);
    if (fib_array == NULL) {
        perror("malloc");
        exit(EXIT_FAILURE);
    }

    // Create thread
    pthread_t fib_thread;
    pthread_create(&fib_thread, NULL, generate_fibonacci, NULL);

    // Wait for the thread to finish
    pthread_join(fib_thread, NULL);

    // Print the Fibonacci sequence
    printf("Fibonacci sequence of %d terms:\n", count);
    for (int i = 0; i < count; i++) {
        printf("%d ", fib_array[i]);
    }
    printf("\n");

    // Cleanup
    free(fib_array);
    return 0;
}

